/**
 * Static utility definitions (non-numeric).
 * Numeric utilities (j-p-12, j-m-7, etc.) are generated generically in patterns.js.
 */
module.exports = {
  /* ===== Layout / Display ===== */
  "j-block": "display: block",
  "j-inline-block": "display: inline-block",
  "j-inline": "display: inline",
  "j-flex": "display: flex",
  "j-inline-flex": "display: inline-flex",
  "j-grid": "display: grid",
  "j-inline-grid": "display: inline-grid",
  "j-flow-root": "display: flow-root",
  "j-contents": "display: contents",
  "j-list-item": "display: list-item",
  "j-table": "display: table",
  "j-table-cell": "display: table-cell",
  "j-table-row": "display: table-row",
  "j-hidden": "display: none",

  /* ===== Box Sizing ===== */
  "j-box-border": "box-sizing: border-box",
  "j-box-content": "box-sizing: content-box",

  /* ===== Position ===== */
  "j-relative": "position: relative",
  "j-absolute": "position: absolute",
  "j-fixed": "position: fixed",
  "j-sticky": "position: sticky",
  "j-static": "position: static",

  /* ===== Inset special ===== */
  "j-inset-0": "top: 0; right: 0; bottom: 0; left: 0",
  "j-inset-auto": "top: auto; right: auto; bottom: auto; left: auto",
  "j-inset-x-0": "left: 0; right: 0",
  "j-inset-y-0": "top: 0; bottom: 0",
  "j-inset-x-auto": "left: auto; right: auto",
  "j-inset-y-auto": "top: auto; bottom: auto",

  /* ===== Visibility ===== */
  "j-visible": "visibility: visible",
  "j-invisible": "visibility: hidden",
  "j-collapse": "visibility: collapse",

  /* ===== Isolation ===== */
  "j-isolate": "isolation: isolate",
  "j-isolation-auto": "isolation: auto",

  /* ===== Float / Clear ===== */
  "j-float-right": "float: right",
  "j-float-left": "float: left",
  "j-float-none": "float: none",
  "j-clear-left": "clear: left",
  "j-clear-right": "clear: right",
  "j-clear-both": "clear: both",
  "j-clear-none": "clear: none",

  /* ===== Flexbox ===== */
  "j-flex-row": "flex-direction: row",
  "j-flex-row-reverse": "flex-direction: row-reverse",
  "j-flex-col": "flex-direction: column",
  "j-flex-col-reverse": "flex-direction: column-reverse",
  "j-flex-wrap": "flex-wrap: wrap",
  "j-flex-wrap-reverse": "flex-wrap: wrap-reverse",
  "j-flex-nowrap": "flex-wrap: nowrap",
  "j-flex-1": "flex: 1 1 0%",
  "j-flex-auto": "flex: 1 1 auto",
  "j-flex-none": "flex: none",
  "j-flex-grow": "flex-grow: 1",
  "j-flex-grow-0": "flex-grow: 0",
  "j-flex-shrink": "flex-shrink: 1",
  "j-flex-shrink-0": "flex-shrink: 0",
  "j-items-start": "align-items: flex-start",
  "j-items-end": "align-items: flex-end",
  "j-items-center": "align-items: center",
  "j-items-stretch": "align-items: stretch",
  "j-items-baseline": "align-items: baseline",
  "j-justify-start": "justify-content: flex-start",
  "j-justify-end": "justify-content: flex-end",
  "j-justify-center": "justify-content: center",
  "j-justify-between": "justify-content: space-between",
  "j-justify-around": "justify-content: space-around",
  "j-justify-evenly": "justify-content: space-evenly",
  "j-justify-stretch": "justify-content: stretch",
  "j-self-auto": "align-self: auto",
  "j-self-start": "align-self: flex-start",
  "j-self-end": "align-self: flex-end",
  "j-self-center": "align-self: center",
  "j-self-stretch": "align-self: stretch",
  "j-self-baseline": "align-self: baseline",
  "j-content-start": "align-content: flex-start",
  "j-content-end": "align-content: flex-end",
  "j-content-center": "align-content: center",
  "j-content-between": "align-content: space-between",
  "j-content-around": "align-content: space-around",
  "j-content-evenly": "align-content: space-evenly",
  "j-content-stretch": "align-content: stretch",

  /* ===== Grid ===== */
  "j-grid-flow-row": "grid-auto-flow: row",
  "j-grid-flow-col": "grid-auto-flow: column",
  "j-grid-flow-dense": "grid-auto-flow: dense",
  "j-grid-flow-row-dense": "grid-auto-flow: row dense",
  "j-grid-flow-col-dense": "grid-auto-flow: column dense",
  "j-auto-cols-auto": "grid-auto-columns: auto",
  "j-auto-cols-min": "grid-auto-columns: min-content",
  "j-auto-cols-max": "grid-auto-columns: max-content",
  "j-auto-cols-fr": "grid-auto-columns: minmax(0, 1fr)",
  "j-auto-rows-auto": "grid-auto-rows: auto",
  "j-auto-rows-min": "grid-auto-rows: min-content",
  "j-auto-rows-max": "grid-auto-rows: max-content",
  "j-auto-rows-fr": "grid-auto-rows: minmax(0, 1fr)",
  "j-col-auto": "grid-column: auto",
  "j-col-span-full": "grid-column: 1 / -1",
  "j-row-auto": "grid-row: auto",
  "j-row-span-full": "grid-row: 1 / -1",
  "j-place-items-start": "place-items: start",
  "j-place-items-end": "place-items: end",
  "j-place-items-center": "place-items: center",
  "j-place-items-stretch": "place-items: stretch",
  "j-place-content-start": "place-content: start",
  "j-place-content-end": "place-content: end",
  "j-place-content-center": "place-content: center",
  "j-place-content-between": "place-content: space-between",
  "j-place-content-around": "place-content: space-around",
  "j-place-content-evenly": "place-content: space-evenly",
  "j-place-content-stretch": "place-content: stretch",
  "j-place-self-auto": "place-self: auto",
  "j-place-self-start": "place-self: start",
  "j-place-self-end": "place-self: end",
  "j-place-self-center": "place-self: center",
  "j-place-self-stretch": "place-self: stretch",

  /* ===== Margin special ===== */
  "j-mx-auto": "margin-left: auto; margin-right: auto",
  "j-my-auto": "margin-top: auto; margin-bottom: auto",
  "j-mt-auto": "margin-top: auto",
  "j-mb-auto": "margin-bottom: auto",
  "j-ml-auto": "margin-left: auto",
  "j-mr-auto": "margin-right: auto",
  "j-m-auto": "margin: auto",

  /* ===== Size special ===== */
  "j-w-full": "width: 100%",
  "j-w-screen": "width: 100vw",
  "j-w-auto": "width: auto",
  "j-w-min": "width: min-content",
  "j-w-max": "width: max-content",
  "j-w-fit": "width: fit-content",
  "j-h-full": "height: 100%",
  "j-h-screen": "height: 100vh",
  "j-h-svh": "height: 100svh",
  "j-h-lvh": "height: 100lvh",
  "j-h-auto": "height: auto",
  "j-h-min": "height: min-content",
  "j-h-max": "height: max-content",
  "j-h-fit": "height: fit-content",
  "j-min-h-screen": "min-height: 100vh",
  "j-min-h-full": "min-height: 100%",
  "j-min-h-0": "min-height: 0",
  "j-max-w-none": "max-width: none",
  "j-max-w-xs": "max-width: 20rem",
  "j-max-w-sm": "max-width: 24rem",
  "j-max-w-md": "max-width: 28rem",
  "j-max-w-lg": "max-width: 32rem",
  "j-max-w-xl": "max-width: 36rem",
  "j-max-w-2xl": "max-width: 42rem",
  "j-max-w-3xl": "max-width: 48rem",
  "j-max-w-4xl": "max-width: 56rem",
  "j-max-w-5xl": "max-width: 64rem",
  "j-max-w-6xl": "max-width: 72rem",
  "j-max-w-7xl": "max-width: 80rem",
  "j-max-w-full": "max-width: 100%",
  "j-max-w-screen": "max-width: 100vw",
  "j-max-w-prose": "max-width: 65ch",
  "j-size-full": "width: 100%; height: 100%",
  "j-size-screen": "width: 100vw; height: 100vh",
  "j-size-auto": "width: auto; height: auto",
  "j-size-min": "width: min-content; height: min-content",
  "j-size-max": "width: max-content; height: max-content",
  "j-size-fit": "width: fit-content; height: fit-content",
  "j-container": "width: 100%; max-width: 1280px; margin-left: auto; margin-right: auto; padding-left: 1rem; padding-right: 1rem",

  /* ===== Typography scale ===== */
  "j-text-xs": "font-size: 0.75rem; line-height: 1rem",
  "j-text-sm": "font-size: 0.875rem; line-height: 1.25rem",
  "j-text-base": "font-size: 1rem; line-height: 1.5rem",
  "j-text-lg": "font-size: 1.125rem; line-height: 1.75rem",
  "j-text-xl": "font-size: 1.25rem; line-height: 1.75rem",
  "j-text-2xl": "font-size: 1.5rem; line-height: 2rem",
  "j-text-3xl": "font-size: 1.875rem; line-height: 2.25rem",
  "j-text-4xl": "font-size: 2.25rem; line-height: 2.5rem",
  "j-text-5xl": "font-size: 3rem; line-height: 1",
  "j-text-6xl": "font-size: 3.75rem; line-height: 1",
  "j-text-7xl": "font-size: 4.5rem; line-height: 1",
  "j-text-8xl": "font-size: 6rem; line-height: 1",
  "j-text-9xl": "font-size: 8rem; line-height: 1",

  /* ===== Font weight ===== */
  "j-font-thin": "font-weight: 100",
  "j-font-extralight": "font-weight: 200",
  "j-font-light": "font-weight: 300",
  "j-font-normal": "font-weight: 400",
  "j-font-medium": "font-weight: 500",
  "j-font-semibold": "font-weight: 600",
  "j-font-bold": "font-weight: 700",
  "j-font-extrabold": "font-weight: 800",
  "j-font-black": "font-weight: 900",

  /* ===== Font family ===== */
  "j-font-sans": "font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif",
  "j-font-serif": "font-family: ui-serif, Georgia, Cambria, 'Times New Roman', Times, serif",
  "j-font-mono": "font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",

  /* ===== Text align ===== */
  "j-text-left": "text-align: left",
  "j-text-center": "text-align: center",
  "j-text-right": "text-align: right",
  "j-text-justify": "text-align: justify",
  "j-text-start": "text-align: start",
  "j-text-end": "text-align: end",

  /* ===== Text transform ===== */
  "j-uppercase": "text-transform: uppercase",
  "j-lowercase": "text-transform: lowercase",
  "j-capitalize": "text-transform: capitalize",
  "j-normal-case": "text-transform: none",

  /* ===== Text decoration ===== */
  "j-underline": "text-decoration-line: underline",
  "j-overline": "text-decoration-line: overline",
  "j-line-through": "text-decoration-line: line-through",
  "j-no-underline": "text-decoration-line: none",

  /* ===== Font style ===== */
  "j-italic": "font-style: italic",
  "j-not-italic": "font-style: normal",

  /* ===== Line height ===== */
  "j-leading-none": "line-height: 1",
  "j-leading-tight": "line-height: 1.25",
  "j-leading-snug": "line-height: 1.375",
  "j-leading-normal": "line-height: 1.5",
  "j-leading-relaxed": "line-height: 1.625",
  "j-leading-loose": "line-height: 2",

  /* ===== Letter spacing ===== */
  "j-tracking-tighter": "letter-spacing: -0.05em",
  "j-tracking-tight": "letter-spacing: -0.025em",
  "j-tracking-normal": "letter-spacing: 0em",
  "j-tracking-wide": "letter-spacing: 0.025em",
  "j-tracking-wider": "letter-spacing: 0.05em",
  "j-tracking-widest": "letter-spacing: 0.1em",

  /* ===== Text overflow / whitespace ===== */
  "j-truncate": "overflow: hidden; text-overflow: ellipsis; white-space: nowrap",
  "j-text-ellipsis": "text-overflow: ellipsis",
  "j-text-clip": "text-overflow: clip",
  "j-whitespace-nowrap": "white-space: nowrap",
  "j-whitespace-normal": "white-space: normal",
  "j-whitespace-pre": "white-space: pre",
  "j-whitespace-pre-line": "white-space: pre-line",
  "j-whitespace-pre-wrap": "white-space: pre-wrap",
  "j-whitespace-break-spaces": "white-space: break-spaces",
  "j-break-words": "overflow-wrap: break-word",
  "j-break-normal": "overflow-wrap: normal; word-break: normal",
  "j-break-all": "word-break: break-all",
  "j-break-keep": "word-break: keep-all",
  "j-hyphens-none": "hyphens: none",
  "j-hyphens-manual": "hyphens: manual",
  "j-hyphens-auto": "hyphens: auto",

  /* ===== Text decoration extras ===== */
  "j-bg-clip-text": "background-clip: text; -webkit-background-clip: text",
  "j-text-transparent": "color: transparent; -webkit-text-fill-color: transparent",

  /* ===== Text colors ===== */
  "j-text-white": "color: #fff",
  "j-text-black": "color: #000",
  "j-text-transparent": "color: transparent",
  "j-text-current": "color: currentColor",
  "j-text-primary": "color: #2563eb",
  "j-text-gray": "color: #6b7280",
  "j-text-blue": "color: #3b82f8",
  "j-text-red": "color: #ef4444",
  "j-text-green": "color: #22c55e",
  "j-text-yellow": "color: #eab308",
  "j-text-orange": "color: #f97316",
  "j-text-pink": "color: #ec4899",
  "j-text-purple": "color: #a855f7",
  "j-text-indigo": "color: #6366f1",
  "j-text-teal": "color: #14b8a6",
  "j-text-cyan": "color: #06b6d4",
  "j-text-slate": "color: #64748b",
  "j-text-rose": "color: #f43f5e",
  "j-text-sky": "color: #0ea5e9",
  "j-text-lime": "color: #84cc16",
  "j-text-emerald": "color: #10b981",
  "j-text-violet": "color: #8b5cf6",
  "j-text-fuchsia": "color: #d946ef",
  "j-text-amber": "color: #f59e0b",
  "j-text-zinc": "color: #71717a",
  "j-text-neutral": "color: #737373",
  "j-text-stone": "color: #78716c",

  /* ===== Background colors ===== */
  "j-bg-white": "background-color: #fff",
  "j-bg-black": "background-color: #000",
  "j-bg-transparent": "background-color: transparent",
  "j-bg-current": "background-color: currentColor",
  "j-bg-primary": "background-color: #2563eb",
  "j-bg-primary-dark": "background-color: #1d4ed8",
  "j-bg-gray": "background-color: #6b7280",
  "j-bg-blue": "background-color: #3b82f8",
  "j-bg-red": "background-color: #ef4444",
  "j-bg-green": "background-color: #22c55e",
  "j-bg-yellow": "background-color: #eab308",
  "j-bg-orange": "background-color: #f97316",
  "j-bg-pink": "background-color: #ec4899",
  "j-bg-purple": "background-color: #a855f7",
  "j-bg-indigo": "background-color: #6366f1",
  "j-bg-teal": "background-color: #14b8a6",
  "j-bg-cyan": "background-color: #06b6d4",
  "j-bg-slate": "background-color: #64748b",
  "j-bg-rose": "background-color: #f43f5e",
  "j-bg-sky": "background-color: #0ea5e9",
  "j-bg-lime": "background-color: #84cc16",
  "j-bg-emerald": "background-color: #10b981",
  "j-bg-violet": "background-color: #8b5cf6",
  "j-bg-fuchsia": "background-color: #d946ef",
  "j-bg-amber": "background-color: #f59e0b",
  "j-bg-zinc": "background-color: #71717a",
  "j-bg-neutral": "background-color: #737373",
  "j-bg-stone": "background-color: #78716c",
  "j-bg-gray-100": "background-color: #f3f4f6",
  "j-bg-gray-200": "background-color: #e5e7eb",

  /* ===== Background size/position/repeat/attachment ===== */
  "j-bg-auto": "background-size: auto",
  "j-bg-cover": "background-size: cover",
  "j-bg-contain": "background-size: contain",
  "j-bg-center": "background-position: center",
  "j-bg-top": "background-position: top",
  "j-bg-bottom": "background-position: bottom",
  "j-bg-left": "background-position: left",
  "j-bg-right": "background-position: right",
  "j-bg-left-top": "background-position: left top",
  "j-bg-left-bottom": "background-position: left bottom",
  "j-bg-right-top": "background-position: right top",
  "j-bg-right-bottom": "background-position: right bottom",
  "j-bg-repeat": "background-repeat: repeat",
  "j-bg-no-repeat": "background-repeat: no-repeat",
  "j-bg-repeat-x": "background-repeat: repeat-x",
  "j-bg-repeat-y": "background-repeat: repeat-y",
  "j-bg-repeat-round": "background-repeat: round",
  "j-bg-repeat-space": "background-repeat: space",
  "j-bg-fixed": "background-attachment: fixed",
  "j-bg-local": "background-attachment: local",
  "j-bg-scroll": "background-attachment: scroll",
  "j-bg-none": "background-image: none",

  /* ===== Border width ===== */
  "j-border": "border-width: 1px; border-style: solid",
  "j-border-0": "border-width: 0; border-style: solid",
  "j-border-2": "border-width: 2px; border-style: solid",
  "j-border-4": "border-width: 4px; border-style: solid",
  "j-border-8": "border-width: 8px; border-style: solid",
  "j-border-t": "border-top-width: 1px; border-top-style: solid",
  "j-border-r": "border-right-width: 1px; border-right-style: solid",
  "j-border-b": "border-bottom-width: 1px; border-bottom-style: solid",
  "j-border-l": "border-left-width: 1px; border-left-style: solid",
  "j-border-t-0": "border-top-width: 0",
  "j-border-r-0": "border-right-width: 0",
  "j-border-b-0": "border-bottom-width: 0",
  "j-border-l-0": "border-left-width: 0",
  "j-border-t-2": "border-top-width: 2px; border-top-style: solid",
  "j-border-r-2": "border-right-width: 2px; border-right-style: solid",
  "j-border-b-2": "border-bottom-width: 2px; border-bottom-style: solid",
  "j-border-l-2": "border-left-width: 2px; border-left-style: solid",
  "j-border-t-4": "border-top-width: 4px; border-top-style: solid",
  "j-border-r-4": "border-right-width: 4px; border-right-style: solid",
  "j-border-b-4": "border-bottom-width: 4px; border-bottom-style: solid",
  "j-border-l-4": "border-left-width: 4px; border-left-style: solid",

  /* ===== Border style ===== */
  "j-border-solid": "border-style: solid",
  "j-border-dashed": "border-style: dashed",
  "j-border-dotted": "border-style: dotted",
  "j-border-double": "border-style: double",
  "j-border-hidden": "border-style: hidden",
  "j-border-none": "border-style: none; border-width: 0",

  /* ===== Border color ===== */
  "j-border-white": "border-color: #fff",
  "j-border-black": "border-color: #000",
  "j-border-transparent": "border-color: transparent",
  "j-border-current": "border-color: currentColor",
  "j-border-gray-200": "border-color: #e5e7eb",
  "j-border-gray-300": "border-color: #d1d5db",

  /* ===== Border radius ===== */
  "j-rounded-none": "border-radius: 0",
  "j-rounded-sm": "border-radius: 0.125rem",
  "j-rounded": "border-radius: 0.25rem",
  "j-rounded-md": "border-radius: 0.375rem",
  "j-rounded-lg": "border-radius: 0.5rem",
  "j-rounded-xl": "border-radius: 0.75rem",
  "j-rounded-2xl": "border-radius: 1rem",
  "j-rounded-3xl": "border-radius: 1.5rem",
  "j-rounded-full": "border-radius: 9999px",
  /* Rounded top */
  "j-rounded-t-none": "border-top-left-radius: 0; border-top-right-radius: 0",
  "j-rounded-t-sm": "border-top-left-radius: 0.125rem; border-top-right-radius: 0.125rem",
  "j-rounded-t": "border-top-left-radius: 0.25rem; border-top-right-radius: 0.25rem",
  "j-rounded-t-md": "border-top-left-radius: 0.375rem; border-top-right-radius: 0.375rem",
  "j-rounded-t-lg": "border-top-left-radius: 0.5rem; border-top-right-radius: 0.5rem",
  "j-rounded-t-xl": "border-top-left-radius: 0.75rem; border-top-right-radius: 0.75rem",
  "j-rounded-t-2xl": "border-top-left-radius: 1rem; border-top-right-radius: 1rem",
  "j-rounded-t-3xl": "border-top-left-radius: 1.5rem; border-top-right-radius: 1.5rem",
  "j-rounded-t-full": "border-top-left-radius: 9999px; border-top-right-radius: 9999px",
  /* Rounded bottom */
  "j-rounded-b-none": "border-bottom-left-radius: 0; border-bottom-right-radius: 0",
  "j-rounded-b-sm": "border-bottom-left-radius: 0.125rem; border-bottom-right-radius: 0.125rem",
  "j-rounded-b": "border-bottom-left-radius: 0.25rem; border-bottom-right-radius: 0.25rem",
  "j-rounded-b-md": "border-bottom-left-radius: 0.375rem; border-bottom-right-radius: 0.375rem",
  "j-rounded-b-lg": "border-bottom-left-radius: 0.5rem; border-bottom-right-radius: 0.5rem",
  "j-rounded-b-xl": "border-bottom-left-radius: 0.75rem; border-bottom-right-radius: 0.75rem",
  "j-rounded-b-2xl": "border-bottom-left-radius: 1rem; border-bottom-right-radius: 1rem",
  "j-rounded-b-3xl": "border-bottom-left-radius: 1.5rem; border-bottom-right-radius: 1.5rem",
  "j-rounded-b-full": "border-bottom-left-radius: 9999px; border-bottom-right-radius: 9999px",
  /* Rounded left */
  "j-rounded-l-none": "border-top-left-radius: 0; border-bottom-left-radius: 0",
  "j-rounded-l-sm": "border-top-left-radius: 0.125rem; border-bottom-left-radius: 0.125rem",
  "j-rounded-l": "border-top-left-radius: 0.25rem; border-bottom-left-radius: 0.25rem",
  "j-rounded-l-md": "border-top-left-radius: 0.375rem; border-bottom-left-radius: 0.375rem",
  "j-rounded-l-lg": "border-top-left-radius: 0.5rem; border-bottom-left-radius: 0.5rem",
  "j-rounded-l-xl": "border-top-left-radius: 0.75rem; border-bottom-left-radius: 0.75rem",
  "j-rounded-l-2xl": "border-top-left-radius: 1rem; border-bottom-left-radius: 1rem",
  "j-rounded-l-full": "border-top-left-radius: 9999px; border-bottom-left-radius: 9999px",
  /* Rounded right */
  "j-rounded-r-none": "border-top-right-radius: 0; border-bottom-right-radius: 0",
  "j-rounded-r-sm": "border-top-right-radius: 0.125rem; border-bottom-right-radius: 0.125rem",
  "j-rounded-r": "border-top-right-radius: 0.25rem; border-bottom-right-radius: 0.25rem",
  "j-rounded-r-md": "border-top-right-radius: 0.375rem; border-bottom-right-radius: 0.375rem",
  "j-rounded-r-lg": "border-top-right-radius: 0.5rem; border-bottom-right-radius: 0.5rem",
  "j-rounded-r-xl": "border-top-right-radius: 0.75rem; border-bottom-right-radius: 0.75rem",
  "j-rounded-r-2xl": "border-top-right-radius: 1rem; border-bottom-right-radius: 1rem",
  "j-rounded-r-full": "border-top-right-radius: 9999px; border-bottom-right-radius: 9999px",
  /* Rounded individual corners */
  "j-rounded-tl-none": "border-top-left-radius: 0",
  "j-rounded-tl-sm": "border-top-left-radius: 0.125rem",
  "j-rounded-tl": "border-top-left-radius: 0.25rem",
  "j-rounded-tl-md": "border-top-left-radius: 0.375rem",
  "j-rounded-tl-lg": "border-top-left-radius: 0.5rem",
  "j-rounded-tl-xl": "border-top-left-radius: 0.75rem",
  "j-rounded-tl-2xl": "border-top-left-radius: 1rem",
  "j-rounded-tl-full": "border-top-left-radius: 9999px",
  "j-rounded-tr-none": "border-top-right-radius: 0",
  "j-rounded-tr-sm": "border-top-right-radius: 0.125rem",
  "j-rounded-tr": "border-top-right-radius: 0.25rem",
  "j-rounded-tr-md": "border-top-right-radius: 0.375rem",
  "j-rounded-tr-lg": "border-top-right-radius: 0.5rem",
  "j-rounded-tr-xl": "border-top-right-radius: 0.75rem",
  "j-rounded-tr-2xl": "border-top-right-radius: 1rem",
  "j-rounded-tr-full": "border-top-right-radius: 9999px",
  "j-rounded-bl-none": "border-bottom-left-radius: 0",
  "j-rounded-bl-sm": "border-bottom-left-radius: 0.125rem",
  "j-rounded-bl": "border-bottom-left-radius: 0.25rem",
  "j-rounded-bl-md": "border-bottom-left-radius: 0.375rem",
  "j-rounded-bl-lg": "border-bottom-left-radius: 0.5rem",
  "j-rounded-bl-xl": "border-bottom-left-radius: 0.75rem",
  "j-rounded-bl-2xl": "border-bottom-left-radius: 1rem",
  "j-rounded-bl-full": "border-bottom-left-radius: 9999px",
  "j-rounded-br-none": "border-bottom-right-radius: 0",
  "j-rounded-br-sm": "border-bottom-right-radius: 0.125rem",
  "j-rounded-br": "border-bottom-right-radius: 0.25rem",
  "j-rounded-br-md": "border-bottom-right-radius: 0.375rem",
  "j-rounded-br-lg": "border-bottom-right-radius: 0.5rem",
  "j-rounded-br-xl": "border-bottom-right-radius: 0.75rem",
  "j-rounded-br-2xl": "border-bottom-right-radius: 1rem",
  "j-rounded-br-full": "border-bottom-right-radius: 9999px",

  /* ===== Shadow ===== */
  "j-shadow-sm": "box-shadow: 0 1px 2px 0 rgb(0 0 0 / 0.05)",
  "j-shadow": "box-shadow: 0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
  "j-shadow-md": "box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
  "j-shadow-lg": "box-shadow: 0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
  "j-shadow-xl": "box-shadow: 0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
  "j-shadow-2xl": "box-shadow: 0 25px 50px -12px rgb(0 0 0 / 0.25)",
  "j-shadow-inner": "box-shadow: inset 0 2px 4px 0 rgb(0 0 0 / 0.05)",
  "j-shadow-none": "box-shadow: none",

  /* ===== Ring utilities ===== */
  "j-ring-0": "box-shadow: 0 0 0 0 rgb(59 130 246 / 0.5)",
  "j-ring-1": "box-shadow: 0 0 0 1px rgb(59 130 246 / 0.5)",
  "j-ring-2": "box-shadow: 0 0 0 2px rgb(59 130 246 / 0.5)",
  "j-ring": "box-shadow: 0 0 0 3px rgb(59 130 246 / 0.5)",
  "j-ring-4": "box-shadow: 0 0 0 4px rgb(59 130 246 / 0.5)",
  "j-ring-8": "box-shadow: 0 0 0 8px rgb(59 130 246 / 0.5)",
  "j-ring-white": "box-shadow: 0 0 0 3px #fff",
  "j-ring-black": "box-shadow: 0 0 0 3px #000",
  "j-ring-transparent": "box-shadow: 0 0 0 3px transparent",
  "j-ring-inset": "--j-ring-inset: inset",
  "j-ring-offset-0": "box-shadow: 0 0 0 0 #fff, 0 0 0 0 rgb(59 130 246 / 0.5)",
  "j-ring-offset-1": "box-shadow: 0 0 0 1px #fff, 0 0 0 4px rgb(59 130 246 / 0.5)",
  "j-ring-offset-2": "box-shadow: 0 0 0 2px #fff, 0 0 0 5px rgb(59 130 246 / 0.5)",
  "j-ring-offset-4": "box-shadow: 0 0 0 4px #fff, 0 0 0 7px rgb(59 130 246 / 0.5)",

  /* ===== Overflow ===== */
  "j-overflow-auto": "overflow: auto",
  "j-overflow-hidden": "overflow: hidden",
  "j-overflow-visible": "overflow: visible",
  "j-overflow-scroll": "overflow: scroll",
  "j-overflow-x-auto": "overflow-x: auto",
  "j-overflow-y-auto": "overflow-y: auto",
  "j-overflow-x-hidden": "overflow-x: hidden",
  "j-overflow-y-hidden": "overflow-y: hidden",
  "j-overflow-x-visible": "overflow-x: visible",
  "j-overflow-y-visible": "overflow-y: visible",
  "j-overflow-x-scroll": "overflow-x: scroll",
  "j-overflow-y-scroll": "overflow-y: scroll",
  "j-overscroll-auto": "overscroll-behavior: auto",
  "j-overscroll-contain": "overscroll-behavior: contain",
  "j-overscroll-none": "overscroll-behavior: none",
  "j-overscroll-x-auto": "overscroll-behavior-x: auto",
  "j-overscroll-x-contain": "overscroll-behavior-x: contain",
  "j-overscroll-x-none": "overscroll-behavior-x: none",
  "j-overscroll-y-auto": "overscroll-behavior-y: auto",
  "j-overscroll-y-contain": "overscroll-behavior-y: contain",
  "j-overscroll-y-none": "overscroll-behavior-y: none",

  /* ===== Object fit / position ===== */
  "j-object-contain": "object-fit: contain",
  "j-object-cover": "object-fit: cover",
  "j-object-fill": "object-fit: fill",
  "j-object-none": "object-fit: none",
  "j-object-scale-down": "object-fit: scale-down",
  "j-object-top": "object-position: top",
  "j-object-bottom": "object-position: bottom",
  "j-object-left": "object-position: left",
  "j-object-right": "object-position: right",
  "j-object-center": "object-position: center",
  "j-object-left-top": "object-position: left top",
  "j-object-left-bottom": "object-position: left bottom",
  "j-object-right-top": "object-position: right top",
  "j-object-right-bottom": "object-position: right bottom",

  /* ===== Transforms ===== */
  "j-transform": "transform: translateX(var(--j-translate-x,0)) translateY(var(--j-translate-y,0)) rotate(var(--j-rotate,0deg)) skewX(var(--j-skew-x,0)) skewY(var(--j-skew-y,0)) scaleX(var(--j-scale-x,1)) scaleY(var(--j-scale-y,1))",
  "j-transform-none": "transform: none",
  "j-transform-gpu": "transform: translate3d(var(--j-translate-x,0),var(--j-translate-y,0),0) rotate(var(--j-rotate,0deg)) skewX(var(--j-skew-x,0)) skewY(var(--j-skew-y,0)) scaleX(var(--j-scale-x,1)) scaleY(var(--j-scale-y,1))",
  "j-origin-center": "transform-origin: center",
  "j-origin-top": "transform-origin: top",
  "j-origin-top-right": "transform-origin: top right",
  "j-origin-right": "transform-origin: right",
  "j-origin-bottom-right": "transform-origin: bottom right",
  "j-origin-bottom": "transform-origin: bottom",
  "j-origin-bottom-left": "transform-origin: bottom left",
  "j-origin-left": "transform-origin: left",
  "j-origin-top-left": "transform-origin: top left",

  /* ===== Filters ===== */
  "j-grayscale": "filter: grayscale(100%)",
  "j-grayscale-0": "filter: grayscale(0)",
  "j-invert": "filter: invert(100%)",
  "j-invert-0": "filter: invert(0)",
  "j-sepia": "filter: sepia(100%)",
  "j-sepia-0": "filter: sepia(0)",
  "j-filter-none": "filter: none",
  "j-drop-shadow-sm": "filter: drop-shadow(0 1px 1px rgb(0 0 0 / 0.05))",
  "j-drop-shadow": "filter: drop-shadow(0 1px 2px rgb(0 0 0 / 0.1)) drop-shadow(0 1px 1px rgb(0 0 0 / 0.06))",
  "j-drop-shadow-md": "filter: drop-shadow(0 4px 3px rgb(0 0 0 / 0.07)) drop-shadow(0 2px 2px rgb(0 0 0 / 0.06))",
  "j-drop-shadow-lg": "filter: drop-shadow(0 10px 8px rgb(0 0 0 / 0.04)) drop-shadow(0 4px 3px rgb(0 0 0 / 0.1))",
  "j-drop-shadow-xl": "filter: drop-shadow(0 20px 13px rgb(0 0 0 / 0.03)) drop-shadow(0 8px 5px rgb(0 0 0 / 0.08))",
  "j-drop-shadow-2xl": "filter: drop-shadow(0 25px 25px rgb(0 0 0 / 0.15))",
  "j-drop-shadow-none": "filter: drop-shadow(0 0 #0000)",
  /* Backdrop filters */
  "j-backdrop-blur": "backdrop-filter: blur(8px)",
  "j-backdrop-filter-none": "backdrop-filter: none",

  /* ===== Transition ===== */
  "j-transition": "transition-property: color, background-color, border-color, text-decoration-color, fill, stroke, opacity, box-shadow, transform, filter, backdrop-filter; transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1); transition-duration: 150ms",
  "j-transition-none": "transition-property: none",
  "j-transition-all": "transition-property: all; transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1); transition-duration: 150ms",
  "j-transition-colors": "transition-property: color, background-color, border-color, text-decoration-color, fill, stroke; transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1); transition-duration: 150ms",
  "j-transition-opacity": "transition-property: opacity; transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1); transition-duration: 150ms",
  "j-transition-shadow": "transition-property: box-shadow; transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1); transition-duration: 150ms",
  "j-transition-transform": "transition-property: transform; transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1); transition-duration: 150ms",
  "j-ease-linear": "transition-timing-function: linear",
  "j-ease-in": "transition-timing-function: cubic-bezier(0.4, 0, 1, 1)",
  "j-ease-out": "transition-timing-function: cubic-bezier(0, 0, 0.2, 1)",
  "j-ease-in-out": "transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1)",

  /* ===== Aspect ratio ===== */
  "j-aspect-auto": "aspect-ratio: auto",
  "j-aspect-square": "aspect-ratio: 1 / 1",
  "j-aspect-video": "aspect-ratio: 16 / 9",

  /* ===== Interactivity ===== */
  "j-cursor-auto": "cursor: auto",
  "j-cursor-pointer": "cursor: pointer",
  "j-cursor-not-allowed": "cursor: not-allowed",
  "j-cursor-default": "cursor: default",
  "j-cursor-move": "cursor: move",
  "j-cursor-wait": "cursor: wait",
  "j-cursor-text": "cursor: text",
  "j-cursor-grab": "cursor: grab",
  "j-cursor-grabbing": "cursor: grabbing",
  "j-cursor-crosshair": "cursor: crosshair",
  "j-cursor-zoom-in": "cursor: zoom-in",
  "j-cursor-zoom-out": "cursor: zoom-out",
  "j-cursor-help": "cursor: help",
  "j-pointer-events-none": "pointer-events: none",
  "j-pointer-events-auto": "pointer-events: auto",
  "j-select-none": "user-select: none",
  "j-select-text": "user-select: text",
  "j-select-all": "user-select: all",
  "j-select-auto": "user-select: auto",
  "j-resize-none": "resize: none",
  "j-resize-both": "resize: both",
  "j-resize-x": "resize: horizontal",
  "j-resize-y": "resize: vertical",
  "j-scroll-auto": "scroll-behavior: auto",
  "j-scroll-smooth": "scroll-behavior: smooth",
  "j-touch-auto": "touch-action: auto",
  "j-touch-none": "touch-action: none",
  "j-touch-pan-x": "touch-action: pan-x",
  "j-touch-pan-y": "touch-action: pan-y",
  "j-touch-manipulation": "touch-action: manipulation",

  /* ===== Accessibility ===== */
  "j-sr-only": "position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0, 0, 0, 0); white-space: nowrap; border-width: 0",
  "j-not-sr-only": "position: static; width: auto; height: auto; padding: 0; margin: 0; overflow: visible; clip: auto; white-space: normal",

  /* ===== Appearance ===== */
  "j-appearance-none": "appearance: none; -webkit-appearance: none",
  "j-appearance-auto": "appearance: auto",
  "j-outline-none": "outline: 2px solid transparent; outline-offset: 2px",
  "j-outline": "outline-style: solid",
  "j-outline-dashed": "outline-style: dashed",
  "j-outline-dotted": "outline-style: dotted",
  "j-outline-double": "outline-style: double",
  "j-outline-hidden": "outline: none",

  /* ===== Mix blend / Isolation ===== */
  "j-mix-blend-normal": "mix-blend-mode: normal",
  "j-mix-blend-multiply": "mix-blend-mode: multiply",
  "j-mix-blend-screen": "mix-blend-mode: screen",
  "j-mix-blend-overlay": "mix-blend-mode: overlay",
  "j-mix-blend-darken": "mix-blend-mode: darken",
  "j-mix-blend-lighten": "mix-blend-mode: lighten",
  "j-mix-blend-difference": "mix-blend-mode: difference",
  "j-mix-blend-exclusion": "mix-blend-mode: exclusion",
  "j-mix-blend-color": "mix-blend-mode: color",
  "j-bg-blend-multiply": "background-blend-mode: multiply",
  "j-bg-blend-screen": "background-blend-mode: screen",
  "j-bg-blend-overlay": "background-blend-mode: overlay",
  "j-bg-blend-normal": "background-blend-mode: normal",

  /* ===== Will change ===== */
  "j-will-change-auto": "will-change: auto",
  "j-will-change-scroll": "will-change: scroll-position",
  "j-will-change-contents": "will-change: contents",
  "j-will-change-transform": "will-change: transform",

  /* ===== Group (for group-hover / group-* parent) ===== */
  "j-group": "position: relative",

  /* ===== Peer (for peer-* sibling) ===== */
  "j-peer": "position: relative",
};
